# Github work-flows for testing the package on
# multi-version python matrix
# Learn the syntax at:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Python package

on:

  push:
    branches:
      - master
      - beta

  pull_request:
    branches:
      - master
      - beta

jobs:

  run-tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        # Run on all available platforms
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        # Run in all versions of python
        python-version: [ '2.x', '3.x', 'pypy-2.7', 'pypy-3.8' ]

    steps:
      # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Setup which version of the python to use
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Install the package using setup.py
      - name: Install Package
        run: python setup.py install

#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt

      - name: Testing on Python ${{ matrix.python-version }}
        run: |
          python -m pywebcopy --tests
